### ISSUE TITLE
PIP install fails on macOS 12.2.1 with Apple M1 chip

### ISSUE THREAD

**Issue by tomhaines** [cheofusi/just_playback#13]
Python: Python 3.9.9
PIP: 22.0.4

PIP install fails with the following error:

```
pip3 install just_playback
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting just_playback
  Using cached just_playback-0.1.6.tar.gz (504 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cffi>=1.0.0 in /opt/homebrew/lib/python3.9/site-packages (from just_playback) (1.15.0)
Requirement already satisfied: tinytag in /opt/homebrew/lib/python3.9/site-packages (from just_playback) (1.8.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.9/site-packages (from cffi>=1.0.0->just_playback) (2.21)
Building wheels for collected packages: just_playback
  Building wheel for just_playback (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-3.9
      creating build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/playback.py -> build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/ma_result.py -> build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/__init__.py -> build/lib.macosx-12-arm64-3.9/just_playback
      running build_ext
      generating cffi module 'build/temp.macosx-12-arm64-3.9/_ma_playback.c'
      creating build/temp.macosx-12-arm64-3.9
      building '_ma_playback' extension
      creating build/temp.macosx-12-arm64-3.9/build
      creating build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9
      creating build/temp.macosx-12-arm64-3.9/just_playback
      creating build/temp.macosx-12-arm64-3.9/just_playback/miniaudio
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DMA_NO_GENERATION=1 -Ijust_playback -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-12-arm64-3.9/_ma_playback.c -o build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9/_ma_playback.o -g1 -O3 -ffast-math -mtune=native -march=native
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for just_playback
  Running setup.py clean for just_playback
Failed to build just_playback
Installing collected packages: just_playback
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for just_playback ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for just_playback did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py:148: SetuptoolsDeprecationWarning: setup_requires is deprecated. Supply build dependencies using PEP 517 pyproject.toml build-requires.
        warnings.warn(
      running install
      /opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-3.9
      creating build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/playback.py -> build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/ma_result.py -> build/lib.macosx-12-arm64-3.9/just_playback
      copying just_playback/__init__.py -> build/lib.macosx-12-arm64-3.9/just_playback
      running build_ext
      generating cffi module 'build/temp.macosx-12-arm64-3.9/_ma_playback.c'
      creating build/temp.macosx-12-arm64-3.9
      building '_ma_playback' extension
      creating build/temp.macosx-12-arm64-3.9/build
      creating build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9
      creating build/temp.macosx-12-arm64-3.9/just_playback
      creating build/temp.macosx-12-arm64-3.9/just_playback/miniaudio
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DMA_NO_GENERATION=1 -Ijust_playback -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-12-arm64-3.9/_ma_playback.c -o build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9/_ma_playback.o -g1 -O3 -ffast-math -mtune=native -march=native
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> just_playback

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by cheofusi** [comment]
Hi Tom,

Thanks for reporting this. It [appears](https://discourse.llvm.org/t/why-does-march-native-not-work-on-apple-m1/2733) that clang doesn't support -march=native on the M1. The next release will take this into account but for now you could

1. download an extract the [source files](https://pypi.org/project/just-playback/0.1.6/#files)
2. remove the last element of the `compiler_args` list  at line 20 of `build_ffi_module.py`
3. recreate a new artifact with `tar -czvf just_playback-0.1.6.tar.gz just_playback-0.1.6/` (make sure to first delete the compressed you downloaded)
4. install the new artifact with `pip install just_playback-0.1.6.tar.gz`

**Comment by tomhaines** [comment]
Thank you. I was able to install using this method.

**Comment by skyventuree** [comment]
I have the same problem but it wasn't the error from clang itself.
```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/soraboken/Downloads/just_playback-0.1.6/setup.py", line 7, in <module>
          setup(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 455, in __init__
          _Distribution.__init__(self, {
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 292, in __init__
          self.finalize_options()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 807, in finalize_options
          ep(self)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "build_ffi_module.py", line 5, in <module>
          ffibuilder = FFI()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cffi/api.py", line 48, in __init__
          import _cffi_backend as backend
      ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_cffi_backend.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_cffi_backend.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```
What should I do?

**Comment by mastanbol** [comment]
If you are using Mac M1 then try the below thing.
    
    `export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
      export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1`
