### ISSUE TITLE
Recurrence of Issue 9 from 0.1.6

### ISSUE THREAD

**Issue by AlterraSystems** [cheofusi/just_playback#22]
## Error
Traceback (most recent call last):
  File "C:\Users\pigeo\ACS\ACS.py", line 184, in <module>
    playback.load_file('Diagnostic_Menu.mp3')
  File "C:\Users\pigeo\AppData\Local\Programs\Python\Python310\lib\site-packages\just_playback\playback.py", line 53, in load_file
    self.__bind(lib.load_file(self.__ma_attrs, path_to_file.encode('utf-8')))
  File "C:\Users\pigeo\AppData\Local\Programs\Python\Python310\lib\site-packages\just_playback\playback.py", line 235, in __bind
    raise MiniaudioError(MA_RESULT_STR[ma_res])
just_playback.ma_result.MiniaudioError: MA_ERROR

## Description
This error is thrown when just_playback tries to play a second audio file.
I see that this bug was patched in version 0.1.6 ([https://github.com/cheofusi/just_playback/issues/9]); it seems to have reappeared in version 0.1.7.

**Comment by AlterraSystems** [comment]
I apologise for creating this issue. The problem was with a corrupted file, nothing to do with _just_playback_ at all.
